name: macOS Builds
# build both intel64 and arm64

on:
  workflow_dispatch:
  push:
    branches: ["**"]     # Run on push to any branch
  pull_request:
    branches: ["**"]     # Run on PR to any branch

jobs:
  build-macos-intel:
    name: Build on macOS Intel64 (x64)
    uses: ./.github/workflows/macos-build-steps.yml
    with:
      runner: macos-13

  build-macos-arm:
    name: Build on macOS ARM64 (Apple Silicon)
    uses: ./.github/workflows/macos-build-steps.yml
    with:
      runner: macos-14
      
  # Optional: Add a job that depends on both builds completing
  # This can be used for additional processing that depends on both builds
#  finalize:
#    needs: [build-macos-intel, build-macos-arm]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Summarize build
#        run: echo "Both Intel and ARM builds completed successfully"